export default {
  ACCOUNTING: "Accounting",
  ACTUARIAL_SCIENCE: "Actuarial Science",
  APPLIED_MATH: "Applied Math",
  APPLIED_SCIENCE: "Applied Science",
  ARCHITECTURE: "Architecture",
  BIOCHEMISTRY: "Biochemistry",
  BIOENGINEERING: "Bioengineering",
  BIOLOGY: "Biology",
  BIOTECHNOLOGY: "Biotechnology",
  BUSINESS: "Business",
  BUSINESS_ANALYTICS: "Business Analytics",
  CHEMICAL_ENGINEERING: "Chemical Engineering",
  CHEMISTRY: "Chemistry",
  CIVIL_ENGINEERING: "Civil Engineering",
  COMMUNICATIONS: "Communications",
  COMPUTER_ENGINEERING: "Computer Engineering",
  COMPUTER_SCIENCE: "Computer Science",
  CRIMINOLOGY: "Criminology",
  CULTURAL_STUDIES: "Cultural Studies",
  DATA_SCIENCE: "Data Science",
  DENTISTRY: "Dentistry",
  EARTH_SCIENCES: "Earth Sciences",
  EAST_ASIAN_STUDIES: "East Asian Studies",
  ECONOMICS: "Economics",
  EDUCATION: "Education",
  ELECTRICAL_ENGINEERING: "Electrical Engineering",
  ENGINEERING: "Engineering",
  ENGINEERING_CHEMISTRY: "Engineering Chemistry",
  ENGINEERING_PHYSICS: "Engineering Physics",
  ENGLISH: "English",
  ENTREPRENEURSHIP: "Entrepreneurship",
  ENVIRONMENT: "Environment",
  ENVIRONMENTAL_ENGINEERING: "Environmental Engineering",
  FILM: "Film",
  FINANCE: "Finance",
  FINE_ARTS: "Fine Arts",
  FOOD_SCIENCE: "Food Science",
  GEOGRAPHY: "Geography",
  GEOLOGICAL_ENGINEERING: "Geological Engineering",
  GENDER_STUDIES: "Gender Studies",
  GRAPHIC_DESIGN: "Graphic Design",
  HEALTH_SCIENCE: "Health Science",
  HISTORY: "History",
  INDUSTRIAL_RELATIONS: "Industrial Relations",
  INFORMATION_SYSTEMS: "Information Systems",
  INTERNATIONAL_DEVELOPMENT: "International Development",
  JOURNALISM: "Journalism",
  KINESIOLOGY: "Kinesiology",
  LAW: "Law",
  LIBERAL_ARTS: "Liberal Arts",
  LIFE_SCIENCES: "Life Sciences",
  LINGUISTICS: "Linguistics",
  LITERATURE: "Literature",
  MANAGEMENT: "Management",
  MATERIALS_ENGINEERING: "Materials Engineering",
  MATHEMATICS: "Mathematics",
  MARKETING: "Marketing",
  MECHANICAL_ENGINEERING: "Mechanical Engineering",
  MECHATRONICS_ENGINEERING: "Mechatronics Engineering",
  MEDICINE: "Medicine",
  MINERAL_ENGINEERING: "Mineral Engineering",
  MINING_ENGINEERING: "Mining Engineering",
  MUSIC: "Music",
  NANOTECHNOLOGY_ENGINEERING: "Nanotechnology Engineering",
  NEUROSCIENCE: "Neuroscience",
  NUCLEAR_ENGINEERING: "Nuclear Engineering",
  NURSING: "Nursing",
  NUTRITION: "Nutrition",
  PETROLEUM_ENGINEERING: "Petroleum Engineering",
  PHARMACOLOGY: "Pharmacology",
  PHILOSOPHY: "Philosophy",
  PHOTOGRAPHY: "Photography",
  PHYSICS: "Physics",
  PHYSIOLOGY: "Physiology",
  POLITICAL_SCIENCE: "Political Science",
  PUBLIC_RELATIONS: "Public Relations",
  PSYCHOLOGY: "Psychology",
  RELIGIOUS_STUDIES: "Religious Studies",
  RETAIL_MANAGEMENT: "Retail Management",
  SOCIAL_WORK: "Social Work",
  SOCIOLOGY: "Sociology",
  SOFTWARE_ENGINEERING: "Software Engineering",
  SUSTAINABILITY: "Sustainability",
  SYSTEMS_DESIGN_ENGINEERING: "Systems Design Engineering",
  STATISTICS: "Statistics",
  THEATRE: "Theatre",
  URBAN_PLANNING: "Urban Planning",
};
